version: "3"
services:
  postgres:
    image: postgres:15.1-bullseye
    environment:
      POSTGRES_DB: Shop
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./psql-init:/docker-entrypoint-initdb.d

