version: "3"

services:
  postgres:
    image: postgres:15.1-bullseye
    environment:
      POSTGRES_DB: dvdrental
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
